spring:
  application:
    name: comma-in-the-schedule
  datasource:
    url: jdbc:mysql://db:3306/comma
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: shimhun99@gmail.com
    password: abojpwmvtzyfdgod
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
jwt:
  secret: mIuzfK3QjxW8tbFb5ZBgCpsdl0QYsdqMTD0X4JzBmFg=